# Build & deploy site to Github Pages
name: Deploy GH Pages only
on:
  push:
    branches:
      - update-dependencies
  workflow_dispatch:

jobs:
  Deploy-Github-Pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      - run: npm ci
      - name: Build Sitemap
        run: npm run prebuild
      - name: Build site
        run: npm run build
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
